# Generated by Django 3.0.8 on 2020-09-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
