# Generated by Django 3.1.1 on 2020-09-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200919_2221'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='movie_data',
        ),
    ]
